<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.doitcore</groupId>
        <artifactId>doitcore-admin</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>doitcore-module-relationship</artifactId>
    <description>客户关系管理模块（存放客户关系管理相关业务功能，例如：客户管理等）</description>

    <dependencies>
        <!-- 公共模块（存放公共工具类，公共配置等） -->
        <dependency>
            <groupId>top.doitcore</groupId>
            <artifactId>doitcore-common</artifactId>
        </dependency>
    </dependencies>

</project>